owner: kotatsuclub
repo: status

assignees:
  - shawntoffel
  
sites:
  - name: Kotatsu Club
    url: https://kotatsu.club/status
    expectedStatusCodes:
      - 200
      - 403

status-website:
  cname: status.kotatsu.club
  name: Kotatsu Club Status
  introTitle: Kotatsu Club

workflowSchedule:
  uptime: "0 1 * * *"
